<?php
function indexTemplate(array $viewData)
{
    $template = <<<EOT
    <!DOCTYPE html>
    <html>
    <head>
    <title>Patrick test project</title>
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/css/bootstrap-theme.min.css" />
    <script src="/js/jquery-1.11.3.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/angular.js"></script>
    <script src="/js/angular-route.js"></script>
    <script src="/js/angular-flash.min.js"></script>
    </head>

    <body>
    <div class="container">
        hello world
    </div>
    </body>
    </html>
EOT;
    return $template;
}
